// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyParser, customerRouter, express, lookupMovie, movieRouter, postgres, rentalRouter;

  express = require('express');

  bodyParser = require('body-parser');

  app = express();

  app.use(bodyParser.json({
    type: 'application/json'
  }));

  postgres = require('./lib/postgres');

  lookupMovie = function(req, res, next) {
    var movieId, sql;
    movieId = req.params.id;
    sql = 'SELECT * FROM movie WHERE id = $1';
    return postgres.client.query(sql, [movieId], function(err, results) {
      if (err) {
        console.error(err);
        res.statusCode = 500;
        return res.json({
          errors: ['Could not retrieve movie']
        });
      }
      if (results.rows.length === 0) {
        res.statusCode = 404;
        return res.json({
          errors: ['Movie not found']
        });
      }
      req.movie = results.rows[0];
      return next();
    });
  };

  movieRouter = express.Router();

  movieRouter.get('/', function(req, res) {
    var limit, page, sql;
    page = parseInt(req.query.page, 10);
    if (isNaN(page) || page < 1) {
      page = 1;
    }
    limit = parseInt(req.query.limit, 10);
    if (isNaN(limit)) {
      limit = 10;
    } else if (limit > 50) {
      limit = 50;
    } else if (limit < 1) {
      limit = 1;
    }
    sql = 'SELECT count(1) FROM movie';
    return postgres.client.query(sql, function(err, result) {
      var count, offset;
      if (err) {
        console.error(err);
        res.statusCode = 500;
        return res.json({
          errors: ['Could not retrieve movies']
        });
      }
      count = parseInt(result.rows[0].count, 10);
      offset = (page - 1) * limit;
      sql = 'SELECT * FROM movie OFFSET $1 LIMIT $2';
      return postgres.client.query(sql, [offset, limit], function(err, result) {
        if (err) {
          console.error(err);
          res.statusCode = 500;
          return res.json({
            errors: ['Could not retreive movies']
          });
        }
        return res.json(result.rows);
      });
    });
  });

  movieRouter.post('/', function(req, res) {
    var data, sql;
    sql = 'INSERT INTO movie( title, overview,release_date, inventory) VALUES ($1,$2,$3,$4) RETURNING id';
    data = [req.body.title, req.body.overview, req.body.release_date, req.body.inventory];
    return postgres.client.query(sql, data, function(err, result) {
      var movieId;
      if (err) {
        console.error(err);
        res.statusCode = 500;
        return res.json({
          errors: ['Failed to create movie']
        });
      }
      movieId = result.rows[0].id;
      sql = 'SELECT * FROM movie WHERE id = $1';
      return postgres.client.query(sql, [movieId], function(err, result) {
        if (err) {
          console.error(err);
          res.statusCode = 500;
          return res.json({
            errors: ['Could not retrieve movie after create']
          });
        }
        res.statusCode = 201;
        return res.json(result.rows[0]);
      });
    });
  });

  movieRouter.get('/:id', lookupMovie, function(req, res) {
    return res.json(req.movie);
  });

  movieRouter.patch('/:id', lookupMovie, function(req, res) {
    var data, movieId, sql;
    movieId = req.params.id;
    sql = 'UPDATE movie SET title=$2, overview=$3, release_date=$4, inventory=$5 WHERE id=$1 RETURNING id';
    data = [movieId, req.body.title, req.body.overview, req.body.release_date, req.body.inventory];
    return postgres.client.query(sql, data, function(err, result) {
      if (err) {
        console.error(err);
        res.statusCode = 500;
        return res.json({
          errors: ['Failed to update movie']
        });
      }
      movieId = result.rows[0].id;
      sql = 'SELECT * FROM movie WHERE id = $1';
      return postgres.client.query(sql, [movieId], function(err, result) {
        if (err) {
          console.error(err);
          res.statusCode = 500;
          return res.json({
            errors: ['Could not retrieve movie after update']
          });
        }
        res.statusCode = 201;
        return res.json(result.rows[0]);
      });
    });
  });

  movieRouter["delete"]('/:id', lookupMovie, function(req, res) {
    var movieId, sql;
    movieId = req.params.id;
    sql = 'DELETE FROM movie WHERE id = $1';
    return postgres.client.query(sql, [movieId], function(err, result) {
      if (err) {
        console.error(err);
        res.statusCode = 500;
        return res.json({
          errors: ['Could not delete movie']
        });
      }
      res.statusCode = 201;
      return res.json({
        messages: ['Movie successfully deleted']
      });
    });
  });

  app.use('/movie', movieRouter);

  customerRouter = express.Router();

  customerRouter.get('/', function(req, res) {});

  customerRouter.post('/', function(req, res) {});

  customerRouter.get('/:id', function(req, res) {});

  customerRouter.patch('/:id', function(req, res) {});

  customerRouter["delete"]('/:id', function(req, res) {});

  app.use('/customer', customerRouter);

  rentalRouter = express.Router();

  rentalRouter.get('/', function(req, res) {});

  rentalRouter.post('/', function(req, res) {});

  rentalRouter.get('/:id', function(req, res) {});

  rentalRouter.patch('/:id', function(req, res) {});

  rentalRouter["delete"]('/:id', function(req, res) {});

  app.use('/rental', rentalRouter);

  app.get('/zomg', function(req, res) {
    return res.send('it still still works!');
  });

  module.exports = app;

}).call(this);
