// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyParser, customerRouter, express, movieRouter, rentalRouter;

  express = require('express');

  bodyParser = require('body-parser');

  app = express();

  movieRouter = express.Router();

  movieRouter.get('/', function(req, res) {});

  movieRouter.post('/', function(req, res) {});

  movieRouter.get('/:id', function(req, res) {});

  movieRouter.patch('/:id', function(req, res) {});

  movieRouter["delete"]('/:id', function(req, res) {});

  app.use('/movie', movieRouter);

  customerRouter = express.Router();

  customerRouter.get('/', function(req, res) {});

  customerRouter.post('/', function(req, res) {});

  customerRouter.get('/:id', function(req, res) {});

  customerRouter.patch('/:id', function(req, res) {});

  customerRouter["delete"]('/:id', function(req, res) {});

  app.use('/customer', customerRouter);

  rentalRouter = express.Router();

  rentalRouter.get('/', function(req, res) {});

  rentalRouter.post('/', function(req, res) {});

  rentalRouter.get('/:id', function(req, res) {});

  rentalRouter.patch('/:id', function(req, res) {});

  rentalRouter["delete"]('/:id', function(req, res) {});

  app.use('/rental', rentalRouter);

  app.get('/zomg', function(req, res) {
    return res.send('it still still works!');
  });

  module.exports = app;

}).call(this);
