// Generated by CoffeeScript 1.10.0
(function() {
  var app, movies;

  app = app || {};

  app.MoviesCollection = Backbone.Collection.extend({
    model: app.singleMovie,
    url: "http://localhost:3000/movie"
  });

  movies = new app.MoviesCollection().fetch();

}).call(this);
