// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = app || {};

  app.allMoviesView = Backbone.View.extend({
    tagName: "section",
    render: function() {
      return this.collection.each(this.addMovie, this);
    },
    addMovie: function(movie) {
      var movieView;
      movieView = new app.singleMovieView({
        model: movie
      });
      return this.$el.append(movieView.render().el);
    }
  });

}).call(this);
