// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = app || {};

  app.singleMovieView = Backbone.View.extend({
    tagName: "article",
    className: "movieListItem",
    template: _.template($("#movieElement").html()),
    render: function() {
      var movieTemplate;
      movieTemplate = this.template(this.model.toJSON());
      return this.$el.html(movieTemplate);
    }
  });

}).call(this);
